// shared/drugs-master.js — 自動生成 by generate_master.py
// 手動修正後は手動管理に切り替えること
const DRUG_MASTER = [
  {
    id: "ca001",
    generic: "アムロジピンベシル酸塩",
    brand: "ノルバスク / アムロジン",
    category: "Ca拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ca002",
    generic: "ニフェジピン（徐放錠）",
    brand: "アダラートCR / アダラートL",
    category: "Ca拮抗薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "ca003",
    generic: "ニフェジピン（普通錠・カプセル）",
    brand: "アダラートカプセル",
    category: "Ca拮抗薬",
    form: "カプセル/錠",
    features: ["crush"],
  },
  {
    id: "ca004",
    generic: "アゼルニジピン",
    brand: "カルブロック",
    category: "Ca拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ca005",
    generic: "シルニジピン",
    brand: "アテレック",
    category: "Ca拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ca006",
    generic: "ベニジピン塩酸塩",
    brand: "コニール",
    category: "Ca拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb001",
    generic: "バルサルタン",
    brand: "ディオバン",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb002",
    generic: "カンデサルタン シレキセチル",
    brand: "ブロプレス",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb003",
    generic: "テルミサルタン",
    brand: "ミカルディス",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb004",
    generic: "ロサルタンカリウム",
    brand: "ニューロタン",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb005",
    generic: "イルベサルタン",
    brand: "アバプロ / イルベタン",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb006",
    generic: "アジルサルタン",
    brand: "アジルバ",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arb007",
    generic: "オルメサルタン メドキソミル",
    brand: "オルメテック",
    category: "ARB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace001",
    generic: "エナラプリルマレイン酸塩",
    brand: "レニベース",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace002",
    generic: "ペリンドプリルエルブミン",
    brand: "コバシル",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace003",
    generic: "イミダプリル塩酸塩",
    brand: "タナトリル",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb001",
    generic: "カルベジロール",
    brand: "アーチスト",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb002",
    generic: "ビソプロロールフマル酸塩",
    brand: "メインテート",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb003",
    generic: "アテノロール",
    brand: "テノーミン",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diu001",
    generic: "フロセミド",
    brand: "ラシックス",
    category: "利尿薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diu002",
    generic: "スピロノラクトン",
    brand: "アルダクトンA",
    category: "利尿薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diu003",
    generic: "トリクロルメチアジド",
    brand: "フルイトラン",
    category: "利尿薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diu004",
    generic: "トラセミド",
    brand: "ルプラック",
    category: "利尿薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aplt001",
    generic: "アスピリン腸溶錠",
    brand: "バイアスピリン",
    category: "抗血小板薬",
    form: "腸溶錠",
    features: ["crush"],
  },
  {
    id: "aplt002",
    generic: "クロピドグレル硫酸塩",
    brand: "プラビックス",
    category: "抗血小板薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aplt003",
    generic: "チカグレロル",
    brand: "ブリリンタ",
    category: "抗血小板薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aplt004",
    generic: "プラスグレル塩酸塩",
    brand: "エフィエント",
    category: "抗血小板薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aplt005",
    generic: "シロスタゾール",
    brand: "プレタール",
    category: "抗血小板薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ac001",
    generic: "ワルファリンカリウム",
    brand: "ワーファリン",
    category: "抗凝固薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "doac001",
    generic: "リバーロキサバン",
    brand: "イグザレルト",
    category: "抗凝固薬（DOAC）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "doac002",
    generic: "アピキサバン",
    brand: "エリキュース",
    category: "抗凝固薬（DOAC）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "doac003",
    generic: "エドキサバントシル酸塩水和物",
    brand: "リクシアナ",
    category: "抗凝固薬（DOAC）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "doac004",
    generic: "ダビガトランエテキシラートメタンスルホン酸塩",
    brand: "プラザキサ",
    category: "抗凝固薬（DOAC）",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "stat001",
    generic: "アトルバスタチンカルシウム水和物",
    brand: "リピトール",
    category: "スタチン",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "stat002",
    generic: "ロスバスタチンカルシウム",
    brand: "クレストール",
    category: "スタチン",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "stat003",
    generic: "ピタバスタチンカルシウム水和物",
    brand: "リバロ",
    category: "スタチン",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "stat004",
    generic: "プラバスタチンナトリウム",
    brand: "メバロチン",
    category: "スタチン",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ppi001",
    generic: "オメプラゾール",
    brand: "オメプラール / オメプラゾン",
    category: "PPI",
    form: "腸溶錠/カプセル",
    features: ["crush"],
  },
  {
    id: "ppi002",
    generic: "ランソプラゾール（OD錠）",
    brand: "タケプロンOD",
    category: "PPI",
    form: "OD錠",
    features: ["crush"],
  },
  {
    id: "ppi003",
    generic: "ラベプラゾールナトリウム（錠）",
    brand: "パリエット（錠）",
    category: "PPI",
    form: "腸溶錠",
    features: ["crush"],
  },
  {
    id: "ppi004",
    generic: "ラベプラゾールナトリウム（顆粒）",
    brand: "パリエット顆粒",
    category: "PPI",
    form: "顆粒",
    features: ["crush"],
  },
  {
    id: "ppi005",
    generic: "エソメプラゾールマグネシウム水和物",
    brand: "ネキシウム",
    category: "PPI",
    form: "カプセル/顆粒",
    features: ["crush"],
  },
  {
    id: "pcab001",
    generic: "ボノプラザンフマル酸塩",
    brand: "タケキャブ",
    category: "P-CAB",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "h2b001",
    generic: "ファモチジン",
    brand: "ガスター",
    category: "H2ブロッカー",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "bgu001",
    generic: "メトホルミン塩酸塩",
    brand: "メトグルコ / グリコラン",
    category: "ビグアナイド薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "su001",
    generic: "グリメピリド",
    brand: "アマリール",
    category: "SU薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dpp4001",
    generic: "シタグリプチンリン酸塩水和物",
    brand: "ジャヌビア / グラクティブ",
    category: "DPP-4阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dpp4002",
    generic: "アログリプチン安息香酸塩",
    brand: "ネシーナ",
    category: "DPP-4阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "sglt2001",
    generic: "エンパグリフロジン",
    brand: "ジャディアンス",
    category: "SGLT2阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "sglt2002",
    generic: "ダパグリフロジンプロピレングリコール水和物",
    brand: "フォシーガ",
    category: "SGLT2阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cai001",
    generic: "エゼチミブ",
    brand: "ゼチーア",
    category: "コレステロール吸収阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "thyr001",
    generic: "レボチロキシンナトリウム水和物",
    brand: "チラーヂンS",
    category: "甲状腺ホルモン薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "atg001",
    generic: "チアマゾール",
    brand: "メルカゾール",
    category: "抗甲状腺薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pd001",
    generic: "レボドパ・カルビドパ配合",
    brand: "メネシット / ネオドパゾール",
    category: "パーキンソン病治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dem001",
    generic: "ドネペジル塩酸塩",
    brand: "アリセプト",
    category: "認知症治療薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "dem002",
    generic: "メマンチン塩酸塩",
    brand: "メマリー",
    category: "認知症治療薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "nrp001",
    generic: "プレガバリン",
    brand: "リリカ",
    category: "神経障害性疼痛治療薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "nrp002",
    generic: "プレガバリン（OD錠）",
    brand: "リリカOD錠",
    category: "神経障害性疼痛治療薬",
    form: "OD錠",
    features: ["crush"],
  },
  {
    id: "tap001",
    generic: "ハロペリドール",
    brand: "セレネース",
    category: "定型抗精神病薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aap001",
    generic: "オランザピン",
    brand: "ジプレキサ",
    category: "非定型抗精神病薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "aap002",
    generic: "アリピプラゾール（OD錠）",
    brand: "エビリファイOD錠",
    category: "非定型抗精神病薬",
    form: "OD錠",
    features: ["crush"],
  },
  {
    id: "aap003",
    generic: "クエチアピンフマル酸塩",
    brand: "セロクエル",
    category: "非定型抗精神病薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aap004",
    generic: "リスペリドン",
    brand: "リスパダール",
    category: "非定型抗精神病薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "ssri001",
    generic: "セルトラリン塩酸塩",
    brand: "ジェイゾロフト",
    category: "SSRI",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ssri002",
    generic: "エスシタロプラムシュウ酸塩",
    brand: "レクサプロ",
    category: "SSRI",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "snri001",
    generic: "デュロキセチン塩酸塩",
    brand: "サインバルタ",
    category: "SNRI",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "snri002",
    generic: "ベンラファキシン塩酸塩",
    brand: "イフェクサーSR",
    category: "SNRI",
    form: "徐放カプセル",
    features: ["crush"],
  },
  {
    id: "bz001",
    generic: "ブロチゾラム",
    brand: "レンドルミン",
    category: "ベンゾジアゼピン系",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "orx001",
    generic: "スボレキサント",
    brand: "ベルソムラ",
    category: "オレキシン受容体拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "orx002",
    generic: "レンボレキサント",
    brand: "デエビゴ",
    category: "オレキシン受容体拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "nbz001",
    generic: "ゾルピデム酒石酸塩",
    brand: "マイスリー",
    category: "非ベンゾジアゼピン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pcn001",
    generic: "アモキシシリン水和物",
    brand: "サワシリン / アモリン",
    category: "ペニシリン系",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "ceph001",
    generic: "セファレキシン",
    brand: "ケフレックス",
    category: "セフェム系",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "mac001",
    generic: "クラリスロマイシン（錠）",
    brand: "クラリス / クラリシッド",
    category: "マクロライド系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "mac002",
    generic: "クラリスロマイシン（ドライシロップ）",
    brand: "クラリシッドDS / クラリスDS",
    category: "マクロライド系",
    form: "ドライシロップ",
    features: ["crush"],
  },
  {
    id: "mac003",
    generic: "アジスロマイシン水和物",
    brand: "ジスロマック",
    category: "マクロライド系",
    form: "錠/カプセル",
    features: ["crush"],
  },
  {
    id: "fq001",
    generic: "レボフロキサシン水和物",
    brand: "クラビット",
    category: "ニューキノロン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "fq002",
    generic: "シプロフロキサシン塩酸塩",
    brand: "シプロキサン",
    category: "ニューキノロン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bpn001",
    generic: "アレンドロン酸ナトリウム水和物",
    brand: "フォサマック / ボナロン",
    category: "ビスフォスフォネート",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bpn002",
    generic: "リセドロン酸ナトリウム水和物",
    brand: "アクトネル / ベネット",
    category: "ビスフォスフォネート",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "vitd001",
    generic: "アルファカルシドール",
    brand: "アルファロール / ワンアルファ",
    category: "活性型ビタミンD3",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "pbca001",
    generic: "炭酸カルシウム",
    brand: "カルタン / 沈降炭酸カルシウム",
    category: "リン吸着薬/Ca補給",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "laxac001",
    generic: "酸化マグネシウム",
    brand: "マグミット / 酸化マグネシウム",
    category: "緩下薬/制酸薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "lax001",
    generic: "センノシド",
    brand: "プルゼニド / センノシド",
    category: "緩下薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pamr001",
    generic: "ナルデメジントシル酸塩",
    brand: "スインプロイク",
    category: "便秘治療薬（PAMORA）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ibs001",
    generic: "リナクロチド",
    brand: "リンゼス",
    category: "便秘型IBS治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "digi001",
    generic: "ジゴキシン",
    brand: "ジゴシン",
    category: "強心配糖体",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arr001",
    generic: "アミオダロン塩酸塩",
    brand: "アンカロン",
    category: "抗不整脈薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cand001",
    generic: "ジルチアゼム塩酸塩（普通錠）",
    brand: "ヘルベッサー（普通錠）",
    category: "Ca拮抗薬（非DHP系）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cand002",
    generic: "ジルチアゼム塩酸塩（徐放カプセル）",
    brand: "ヘルベッサーRカプセル",
    category: "Ca拮抗薬（非DHP系）",
    form: "徐放カプセル",
    features: ["crush"],
  },
  {
    id: "ca007",
    generic: "ニカルジピン塩酸塩",
    brand: "ペルジピン",
    category: "Ca拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cand003",
    generic: "ベラパミル塩酸塩",
    brand: "ワソラン",
    category: "Ca拮抗薬（非DHP系）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "angn001",
    generic: "ニコランジル",
    brand: "シグマート",
    category: "狭心症治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arr002",
    generic: "フレカイニド酢酸塩",
    brand: "タンボコール",
    category: "抗不整脈薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arr003",
    generic: "ピルシカイニド塩酸塩水和物",
    brand: "サンリズム",
    category: "抗不整脈薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "chf001",
    generic: "イバブラジン塩酸塩",
    brand: "コララン",
    category: "慢性心不全治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "arni001",
    generic: "サクビトリル バルサルタンナトリウム水和物",
    brand: "エンレスト",
    category: "ARNi",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace004",
    generic: "リシノプリル水和物",
    brand: "ゼストリル / ロンゲス",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace005",
    generic: "カプトプリル",
    brand: "カプトリル",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace006",
    generic: "テモカプリル塩酸塩",
    brand: "エースコール",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace007",
    generic: "デラプリル塩酸塩",
    brand: "アデカット",
    category: "ACE阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ace008",
    generic: "トランドラプリル",
    brand: "オドリック",
    category: "ACE阻害薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "bb004",
    generic: "メトプロロール酒石酸塩",
    brand: "セロケン / ロプレソール",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb005",
    generic: "プロプラノロール塩酸塩",
    brand: "インデラル",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb006",
    generic: "セリプロロール塩酸塩",
    brand: "セレクトール",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb007",
    generic: "ベタキソロール塩酸塩",
    brand: "ケルロング",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bb008",
    generic: "ナドロール",
    brand: "ナジフィール",
    category: "β遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "mra001",
    generic: "エプレレノン",
    brand: "セララ",
    category: "MRA（利尿薬）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "avp001",
    generic: "トルバプタン",
    brand: "サムスカ",
    category: "バソプレシンV2受容体拮抗薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diul001",
    generic: "アゾセミド",
    brand: "ダイアート",
    category: "利尿薬（ループ）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diuts001",
    generic: "インダパミド",
    brand: "ナトリックス",
    category: "利尿薬（チアジド類似）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "diutz001",
    generic: "ヒドロクロロチアジド",
    brand: "ヒドロクロロチアジド",
    category: "利尿薬（チアジド）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "tzd001",
    generic: "ピオグリタゾン塩酸塩",
    brand: "アクトス",
    category: "チアゾリジン薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "agi001",
    generic: "ボグリボース",
    brand: "ベイスン",
    category: "α-GI薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "agi002",
    generic: "ミグリトール",
    brand: "セイブル",
    category: "α-GI薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dpp4003",
    generic: "テネリグリプチン臭化水素酸塩水和物",
    brand: "テネリア",
    category: "DPP-4阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dpp4004",
    generic: "リナグリプチン",
    brand: "トラゼンタ",
    category: "DPP-4阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dpp4005",
    generic: "ビルダグリプチン",
    brand: "エクア",
    category: "DPP-4阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "dpp4006",
    generic: "サキサグリプチン水和物",
    brand: "オングリザ",
    category: "DPP-4阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "sglt2003",
    generic: "イプラグリフロジン L-プロリン",
    brand: "スーグラ",
    category: "SGLT2阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "sglt2004",
    generic: "ルセオグリフロジン水和物",
    brand: "ルセフィ",
    category: "SGLT2阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "sglt2005",
    generic: "トホグリフロジン水和物",
    brand: "アプルウェイ / デベルザ",
    category: "SGLT2阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "su002",
    generic: "グリベンクラミド",
    brand: "オイグルコン / ダオニール",
    category: "SU薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "su003",
    generic: "グリクラジド",
    brand: "グリミクロン",
    category: "SU薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "prok001",
    generic: "モサプリドクエン酸塩水和物",
    brand: "ガスモチン",
    category: "消化管運動促進薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "prok002",
    generic: "ドンペリドン",
    brand: "ナウゼリン",
    category: "消化管運動促進薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "prok003",
    generic: "メトクロプラミド塩酸塩水和物",
    brand: "プリンペラン",
    category: "消化管運動促進薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "gmp001",
    generic: "レバミピド",
    brand: "ムコスタ",
    category: "胃粘膜保護薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "gmp002",
    generic: "テプレノン",
    brand: "セルベックス",
    category: "胃粘膜保護薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "h2b002",
    generic: "ラフチジン",
    brand: "プロテカジン",
    category: "H2ブロッカー",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "h2b003",
    generic: "シメチジン",
    brand: "タガメット",
    category: "H2ブロッカー",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "h2b004",
    generic: "ニザチジン",
    brand: "アシノン",
    category: "H2ブロッカー",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "gmp003",
    generic: "スクラルファート水和物",
    brand: "アルサルミン",
    category: "胃粘膜保護薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "antid001",
    generic: "ロペラミド塩酸塩",
    brand: "ロペミン",
    category: "止瀉薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "bile_seq001",
    generic: "コレスチミド",
    brand: "コレバイン",
    category: "コレステロール低下薬（陰イオン交換樹脂）",
    form: "錠/細粒",
    features: ["crush"],
  },
  {
    id: "apn001",
    generic: "アセトアミノフェン",
    brand: "カロナール",
    category: "解熱鎮痛薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "nsaid001",
    generic: "ロキソプロフェンナトリウム水和物",
    brand: "ロキソニン",
    category: "NSAIDs",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cox2001",
    generic: "セレコキシブ",
    brand: "セレコックス",
    category: "NSAIDs（COX-2選択的）",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "nsaid002",
    generic: "ジクロフェナクナトリウム（腸溶錠）",
    brand: "ボルタレン（錠）",
    category: "NSAIDs",
    form: "腸溶錠",
    features: ["crush"],
  },
  {
    id: "nsaid003",
    generic: "ジクロフェナクナトリウム（徐放カプセル）",
    brand: "ボルタレンSRカプセル",
    category: "NSAIDs",
    form: "徐放カプセル",
    features: ["crush"],
  },
  {
    id: "cox2002",
    generic: "メロキシカム",
    brand: "モービック",
    category: "NSAIDs（COX-2選択的）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "nsaid004",
    generic: "エトドラク",
    brand: "オステラック / ハイペン",
    category: "NSAIDs",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "wopi001",
    generic: "トラマドール塩酸塩（普通錠/カプセル）",
    brand: "トラマール",
    category: "弱オピオイド鎮痛薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "wopi002",
    generic: "トラマドール塩酸塩（徐放錠）",
    brand: "ワントラム",
    category: "弱オピオイド鎮痛薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "sopi001",
    generic: "オキシコドン塩酸塩水和物（徐放錠）",
    brand: "オキシコンチンTR",
    category: "強オピオイド鎮痛薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "sopi002",
    generic: "モルヒネ硫酸塩（徐放錠）",
    brand: "MSコンチン / カディアン",
    category: "強オピオイド鎮痛薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "nrp003",
    generic: "ミロガバリンベシル酸塩",
    brand: "タリージェ",
    category: "神経障害性疼痛治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "a1b001",
    generic: "タムスロシン塩酸塩（OD錠）",
    brand: "ハルナールD",
    category: "α1遮断薬",
    form: "OD錠",
    features: ["crush"],
  },
  {
    id: "a1b002",
    generic: "シロドシン",
    brand: "ユリーフ",
    category: "α1遮断薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "a1b003",
    generic: "ナフトピジル",
    brand: "フリバス",
    category: "α1遮断薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "a5r001",
    generic: "フィナステリド",
    brand: "プロスカー",
    category: "5α還元酵素阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "a5r002",
    generic: "デュタステリド",
    brand: "アボルブ",
    category: "5α還元酵素阻害薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "oabac001",
    generic: "ソリフェナシンコハク酸塩",
    brand: "ベシケア",
    category: "抗コリン薬（過活動膀胱）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "oabac002",
    generic: "イミダフェナシン",
    brand: "ウリトス / ステーブラ",
    category: "抗コリン薬（過活動膀胱）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "b3ag001",
    generic: "ミラベグロン",
    brand: "ベタニス",
    category: "β3受容体作動薬（過活動膀胱）",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "b3ag002",
    generic: "ビベグロン",
    brand: "ベオーバ",
    category: "β3受容体作動薬（過活動膀胱）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aed001",
    generic: "カルバマゼピン",
    brand: "テグレトール",
    category: "抗てんかん薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aed002",
    generic: "バルプロ酸ナトリウム（普通錠）",
    brand: "デパケン / バレリン（普通錠）",
    category: "抗てんかん薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aed003",
    generic: "バルプロ酸ナトリウム（徐放錠）",
    brand: "デパケンR / セレニカR",
    category: "抗てんかん薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "aed004",
    generic: "レベチラセタム",
    brand: "イーケプラ",
    category: "抗てんかん薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aed005",
    generic: "ラモトリギン",
    brand: "ラミクタール",
    category: "抗てんかん薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aed006",
    generic: "ガバペンチン",
    brand: "ガバペン",
    category: "抗てんかん薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "aed007",
    generic: "クロナゼパム",
    brand: "リボトリール / ランドセン",
    category: "抗てんかん薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aed008",
    generic: "ゾニサミド",
    brand: "エクセグラン",
    category: "抗てんかん薬",
    form: "錠/カプセル",
    features: ["crush"],
  },
  {
    id: "aed009",
    generic: "フェニトイン",
    brand: "アレビアチン / ヒダントール",
    category: "抗てんかん薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pd002",
    generic: "プラミペキソール塩酸塩水和物（普通錠）",
    brand: "ビ・シフロール",
    category: "パーキンソン病治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pd003",
    generic: "プラミペキソール塩酸塩水和物（徐放錠）",
    brand: "ミラペックスLA",
    category: "パーキンソン病治療薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "pd004",
    generic: "ロピニロール塩酸塩（普通錠）",
    brand: "レキップ（普通錠）",
    category: "パーキンソン病治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pd005",
    generic: "ロピニロール塩酸塩（徐放錠）",
    brand: "レキップCR",
    category: "パーキンソン病治療薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "pdcomt001",
    generic: "エンタカポン",
    brand: "コムタン",
    category: "パーキンソン病治療薬（COMT阻害薬）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pd006",
    generic: "アマンタジン塩酸塩",
    brand: "シンメトレル",
    category: "パーキンソン病治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ssri003",
    generic: "パロキセチン塩酸塩水和物（普通錠）",
    brand: "パキシル",
    category: "SSRI",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ssri004",
    generic: "パロキセチン塩酸塩水和物（CR錠）",
    brand: "パキシルCR",
    category: "SSRI",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "ssri005",
    generic: "フルボキサミンマレイン酸塩",
    brand: "ルボックス / デプロメール",
    category: "SSRI",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "nassa001",
    generic: "ミルタザピン",
    brand: "リフレックス / レメロン",
    category: "NaSSA",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "tca001",
    generic: "アミトリプチリン塩酸塩",
    brand: "トリプタノール",
    category: "三環系抗うつ薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "tca002",
    generic: "ノルトリプチリン塩酸塩",
    brand: "ノリトレン",
    category: "三環系抗うつ薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "smod001",
    generic: "ボルチオキセチン臭化水素酸塩",
    brand: "トリンテリックス",
    category: "セロトニンモジュレーター",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "aap005",
    generic: "パリペリドン",
    brand: "インヴェガ",
    category: "非定型抗精神病薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "aap006",
    generic: "ブロナンセリン",
    brand: "ロナセン",
    category: "非定型抗精神病薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "tap002",
    generic: "クロルプロマジン塩酸塩",
    brand: "コントミン / ウインタミン",
    category: "定型抗精神病薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "tap003",
    generic: "スルピリド",
    brand: "ドグマチール",
    category: "定型抗精神病薬",
    form: "カプセル/錠",
    features: ["crush"],
  },
  {
    id: "bzs001",
    generic: "ニトラゼパム",
    brand: "ベンザリン / ネルボン",
    category: "ベンゾジアゼピン系睡眠薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bzs002",
    generic: "トリアゾラム",
    brand: "ハルシオン",
    category: "ベンゾジアゼピン系睡眠薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bzs003",
    generic: "フルニトラゼパム",
    brand: "サイレース / ロヒプノール",
    category: "ベンゾジアゼピン系睡眠薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "mlt001",
    generic: "ラメルテオン",
    brand: "ロゼレム",
    category: "メラトニン受容体作動薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "nbzs001",
    generic: "エスゾピクロン",
    brand: "ルネスタ",
    category: "非ベンゾジアゼピン系睡眠薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "tet001",
    generic: "ミノサイクリン塩酸塩",
    brand: "ミノマイシン",
    category: "テトラサイクリン系",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "nitr001",
    generic: "メトロニダゾール",
    brand: "フラジール",
    category: "ニトロイミダゾール系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "azl001",
    generic: "フルコナゾール",
    brand: "ジフルカン",
    category: "トリアゾール系抗真菌薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "azl002",
    generic: "ボリコナゾール",
    brand: "ブイフェンド",
    category: "トリアゾール系抗真菌薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "sulfa001",
    generic: "スルファメトキサゾール・トリメトプリム",
    brand: "バクタ",
    category: "サルファ剤配合",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "tet002",
    generic: "ドキシサイクリン塩酸塩水和物",
    brand: "ビブラマイシン",
    category: "テトラサイクリン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "exp001",
    generic: "カルボシステイン",
    brand: "ムコダイン",
    category: "去痰薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "exp002",
    generic: "アンブロキソール塩酸塩（普通錠）",
    brand: "ムコソルバン（錠）",
    category: "去痰薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "exp003",
    generic: "アンブロキソール塩酸塩（徐放カプセル）",
    brand: "ムコソルバンLカプセル / コントレックス",
    category: "去痰薬",
    form: "徐放カプセル",
    features: ["crush"],
  },
  {
    id: "xan001",
    generic: "テオフィリン（徐放錠/カプセル）",
    brand: "テオドール / テオロング",
    category: "キサンチン系気管支拡張薬",
    form: "徐放錠/カプセル",
    features: ["crush"],
  },
  {
    id: "ltra001",
    generic: "モンテルカストナトリウム",
    brand: "シングレア / キプレス",
    category: "ロイコトリエン受容体拮抗薬",
    form: "錠/OD錠/細粒",
    features: ["crush"],
  },
  {
    id: "ltra002",
    generic: "プランルカスト水和物",
    brand: "オノン",
    category: "ロイコトリエン受容体拮抗薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "xoi001",
    generic: "アロプリノール",
    brand: "ザイロリック / アロシトール",
    category: "キサンチンオキシダーゼ阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "xoi002",
    generic: "フェブキソスタット",
    brand: "フェブリク",
    category: "キサンチンオキシダーゼ阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "xoi003",
    generic: "トピロキソスタット",
    brand: "トピロリック / ウリアデック",
    category: "キサンチンオキシダーゼ阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "gout001",
    generic: "コルヒチン",
    brand: "コルヒチン",
    category: "痛風発作治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cs001",
    generic: "プレドニゾロン",
    brand: "プレドニン",
    category: "副腎皮質ステロイド",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cs002",
    generic: "メチルプレドニゾロン",
    brand: "メドロール",
    category: "副腎皮質ステロイド",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "cs003",
    generic: "デキサメタゾン",
    brand: "デカドロン",
    category: "副腎皮質ステロイド",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "imm001",
    generic: "タクロリムス水和物",
    brand: "プログラフ",
    category: "免疫抑制薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "tb001",
    generic: "リファンピシン",
    brand: "リファジン",
    category: "抗結核薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "ibd001",
    generic: "メサラジン（徐放錠）",
    brand: "ペンタサ（錠） / アサコール",
    category: "炎症性腸疾患治療薬",
    form: "徐放錠",
    features: ["crush"],
  },
  {
    id: "ibd002",
    generic: "メサラジン（顆粒）",
    brand: "ペンタサ顆粒",
    category: "炎症性腸疾患治療薬",
    form: "顆粒",
    features: ["crush"],
  },
  {
    id: "dem003",
    generic: "ガランタミン臭化水素酸塩",
    brand: "レミニール",
    category: "認知症治療薬",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "ceph2001",
    generic: "セファクロル",
    brand: "ケフラール",
    category: "セフェム系（第2世代）",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "pcnc001",
    generic: "アモキシシリン水和物/クラブラン酸カリウム",
    brand: "オーグメンチン配合錠",
    category: "ペニシリン系配合剤",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ceph3001",
    generic: "セフジニル",
    brand: "セフゾン",
    category: "セフェム系（第3世代）",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "ceph3002",
    generic: "セフカペンピボキシル塩酸塩水和物",
    brand: "フロモックス",
    category: "セフェム系（第3世代）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pnm001",
    generic: "ファロペネムナトリウム水和物",
    brand: "ファロム",
    category: "ペネム系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ceph3003",
    generic: "セフポドキシムプロキセチル",
    brand: "バナン",
    category: "セフェム系（第3世代）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ceph2002",
    generic: "セフォテラムピボキシル",
    brand: "パンスポリン",
    category: "セフェム系（第2世代）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "linc001",
    generic: "クリンダマイシン塩酸塩",
    brand: "ダラシンカプセル",
    category: "リンコマイシン系",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "ah2001",
    generic: "フェキソフェナジン塩酸塩",
    brand: "アレグラ",
    category: "抗ヒスタミン薬（第2世代）",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "ah2002",
    generic: "セチリジン塩酸塩",
    brand: "ジルテック",
    category: "抗ヒスタミン薬（第2世代）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ah2003",
    generic: "ロラタジン",
    brand: "クラリチン",
    category: "抗ヒスタミン薬（第2世代）",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "ah2004",
    generic: "オロパタジン塩酸塩",
    brand: "アレロック",
    category: "抗ヒスタミン薬（第2世代）",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "ah2005",
    generic: "ベポタスチンベシル酸塩",
    brand: "タリオン",
    category: "抗ヒスタミン薬（第2世代）",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "ah1001",
    generic: "ジフェンヒドラミン塩酸塩",
    brand: "レスタミンコーワ",
    category: "抗ヒスタミン薬（第1世代）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "ah2006",
    generic: "エピナスチン塩酸塩",
    brand: "アレジオン",
    category: "抗ヒスタミン薬（第2世代）",
    form: "錠/OD錠",
    features: ["crush"],
  },
  {
    id: "tbz001",
    generic: "エチゾラム",
    brand: "デパス",
    category: "チエノジアゼピン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bz002",
    generic: "ジアゼパム",
    brand: "セルシン / ホリゾン",
    category: "ベンゾジアゼピン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bz003",
    generic: "ロラゼパム",
    brand: "ワイパックス",
    category: "ベンゾジアゼピン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bz004",
    generic: "アルプラゾラム",
    brand: "ソラナックス / コンスタン",
    category: "ベンゾジアゼピン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "barb001",
    generic: "フェノバルビタール",
    brand: "フェノバール",
    category: "バルビツール酸系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "bz005",
    generic: "クロキサゾラム",
    brand: "セパゾン",
    category: "ベンゾジアゼピン系",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "5ht1a001",
    generic: "タンドスピロンクエン酸塩",
    brand: "セディール",
    category: "セロトニン1A受容体作動薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pba001",
    generic: "炭酸ランタン水和物",
    brand: "ホスレノール",
    category: "リン吸着薬",
    form: "チュアブル錠/OD錠/顆粒",
    features: ["crush"],
  },
  {
    id: "pba002",
    generic: "セベラマー塩酸塩",
    brand: "フォスブロック / レナジェル",
    category: "リン吸着薬",
    form: "錠/顆粒",
    features: ["crush"],
  },
  {
    id: "pba003",
    generic: "クエン酸第二鉄水和物",
    brand: "リオナ",
    category: "リン吸着薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pba004",
    generic: "ビキサロマー",
    brand: "キックリン",
    category: "リン吸着薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "pba005",
    generic: "スクロオキシ水酸化鉄",
    brand: "ピートル",
    category: "リン吸着薬",
    form: "チュアブル錠/顆粒",
    features: ["crush"],
  },
  {
    id: "gmpz001",
    generic: "ポラプレジンク",
    brand: "プロマック",
    category: "胃粘膜保護薬（亜鉛含有）",
    form: "顆粒",
    features: ["crush"],
  },
  {
    id: "bile001",
    generic: "ウルソデオキシコール酸",
    brand: "ウルソ",
    category: "胆汁酸製剤",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pi001",
    generic: "カモスタットメシル酸塩",
    brand: "フォイパン",
    category: "蛋白分解酵素阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "giac001",
    generic: "ブチルスコポラミン臭化物",
    brand: "ブスコパン",
    category: "抗コリン薬（消化器）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pge1001",
    generic: "ミソプロストール",
    brand: "サイトテック",
    category: "プロスタグランジンE1誘導体",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pdac001",
    generic: "トリヘキシフェニジル塩酸塩",
    brand: "アーテン",
    category: "パーキンソン病治療薬（抗コリン薬）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pdne001",
    generic: "ドロキシドパ",
    brand: "ドプス",
    category: "パーキンソン病治療薬（ノルエピネフリン前駆体）",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "pd007",
    generic: "ゾニサミド（パーキンソン病用）",
    brand: "トレリーフ",
    category: "パーキンソン病治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "pdac002",
    generic: "ビペリデン塩酸塩",
    brand: "アキネトン",
    category: "パーキンソン病治療薬（抗コリン薬）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "atg002",
    generic: "プロピルチオウラシル",
    brand: "チウラジール / プロパジール",
    category: "抗甲状腺薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "carz001",
    generic: "アセタゾラミド",
    brand: "ダイアモックス",
    category: "炭酸脱水酵素阻害薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "oabac003",
    generic: "オキシブチニン塩酸塩（内服）",
    brand: "ポラキス",
    category: "抗コリン薬（過活動膀胱）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "oabac004",
    generic: "トルテロジン酒石酸塩",
    brand: "デトルシトール",
    category: "抗コリン薬（過活動膀胱）",
    form: "徐放カプセル",
    features: ["crush"],
  },
  {
    id: "vert001",
    generic: "ベタヒスチンメシル酸塩",
    brand: "メリスロン",
    category: "めまい治療薬",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "csext001",
    generic: "ジフルプレドナート",
    brand: "マイザー",
    category: "副腎皮質ステロイド（外用）",
    form: "外用",
    features: ["crush"],
  },
  {
    id: "azl003",
    generic: "イトラコナゾール",
    brand: "イトリゾール",
    category: "トリアゾール系抗真菌薬",
    form: "カプセル",
    features: ["crush"],
  },
  {
    id: "digi002",
    generic: "ジゴキシン（散）",
    brand: "ジゴシン散",
    category: "強心配糖体",
    form: "散",
    features: ["crush"],
  },
  {
    id: "mrel001",
    generic: "バクロフェン",
    brand: "リオレサール / ギャバロン",
    category: "筋弛緩薬（中枢性）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "mrel002",
    generic: "チザニジン塩酸塩",
    brand: "テルネリン",
    category: "筋弛緩薬（中枢性）",
    form: "錠",
    features: ["crush"],
  },
  {
    id: "vcm",
    generic: "バンコマイシン",
    brand: "塩酸バンコマイシン",
    category: "抗MRSA薬・グリコペプチド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "teic",
    generic: "テイコプラニン",
    brand: "タルゴシッド",
    category: "抗MRSA薬・グリコペプチド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "gm",
    generic: "ゲンタマイシン",
    brand: "ゲンタシン",
    category: "アミノグリコシド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "amk",
    generic: "アミカシン",
    brand: "アミカシン硫酸塩",
    category: "アミノグリコシド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "abk",
    generic: "アルベカシン",
    brand: "ハベカシン",
    category: "アミノグリコシド系（国内特有）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "mepm",
    generic: "メロペネム",
    brand: "メロペン",
    category: "カルバペネム系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "ipm",
    generic: "イミペネム/シラスタチン",
    brand: "チエナム",
    category: "カルバペネム系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "drpm",
    generic: "ドリペネム",
    brand: "フィニバックス",
    category: "カルバペネム系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "pipc_taz",
    generic: "ピペラシリン/タゾバクタム",
    brand: "タゾシン / ゾシン",
    category: "ペニシリン系（βラクタマーゼ阻害薬配合）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "abpc_sbt",
    generic: "アンピシリン/スルバクタム",
    brand: "スルバシリン / ユナシン",
    category: "ペニシリン系（βラクタマーゼ阻害薬配合）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "ampc",
    generic: "アモキシシリン",
    brand: "アモキシシリン水和物 / サワシリン / パセトシン",
    category: "ペニシリン系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "cez",
    generic: "セファゾリン",
    brand: "セファゾリンナトリウム / セファメジン",
    category: "第1世代セフェム",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "cmz",
    generic: "セフメタゾール",
    brand: "セフメタゾンナトリウム / セフメタゾン",
    category: "セファマイシン系（第2世代相当）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "ctrx",
    generic: "セフトリアキソン",
    brand: "ロセフィン",
    category: "第3世代セフェム",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "caz",
    generic: "セフタジジム",
    brand: "モダシン",
    category: "第3世代セフェム（緑膿菌活性）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "cfpm",
    generic: "セフェピム",
    brand: "マキシピーム",
    category: "第4世代セフェム",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "lzd",
    generic: "リネゾリド",
    brand: "ザイボックス",
    category: "オキサゾリジノン系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "dap",
    generic: "ダプトマイシン",
    brand: "キュビシン",
    category: "環状リポペプチド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "lvfx",
    generic: "レボフロキサシン",
    brand: "クラビット",
    category: "フルオロキノロン系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "cpfx",
    generic: "シプロフロキサシン",
    brand: "シプロキサン",
    category: "フルオロキノロン系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "st",
    generic: "ST合剤",
    brand: "トリメトプリム/スルファメトキサゾール / バクタ / バクトラミン",
    category: "サルファ剤/葉酸代謝拮抗薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "mino",
    generic: "ミノサイクリン",
    brand: "ミノマイシン",
    category: "テトラサイクリン系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "azm",
    generic: "アジスロマイシン",
    brand: "ジスロマック",
    category: "マクロライド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "cam",
    generic: "クラリスロマイシン",
    brand: "クラリス / クラリシッド",
    category: "マクロライド系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "mnz",
    generic: "メトロニダゾール",
    brand: "フラジール / アネメトロ",
    category: "ニトロイミダゾール系",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "flcz",
    generic: "フルコナゾール",
    brand: "ジフルカン",
    category: "トリアゾール系抗真菌薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "vrcz",
    generic: "ボリコナゾール",
    brand: "ブイフェンド",
    category: "トリアゾール系抗真菌薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "mcfg",
    generic: "ミカファンギン",
    brand: "ファンガード",
    category: "キャンディン系抗真菌薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "acv",
    generic: "アシクロビル",
    brand: "アシクロビル点滴静注 / ゾビラックス",
    category: "抗ヘルペス薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "vacv",
    generic: "バラシクロビル",
    brand: "バルトレックス",
    category: "抗ヘルペス薬（アシクロビルプロドラッグ）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "gcv",
    generic: "ガンシクロビル",
    brand: "デノシン",
    category: "抗CMV薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "vgcv",
    generic: "バルガンシクロビル",
    brand: "バリキサ",
    category: "抗CMV薬（ガンシクロビルプロドラッグ）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "otv",
    generic: "オセルタミビル",
    brand: "タミフル",
    category: "抗インフルエンザ薬（ノイラミニダーゼ阻害薬）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "dgx",
    generic: "ジゴキシン",
    brand: "ジゴシン / ラニラピッド",
    category: "強心配糖体",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "aten",
    generic: "アテノロール",
    brand: "テノーミン",
    category: "β1選択的遮断薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "biso",
    generic: "ビソプロロール",
    brand: "メインテート",
    category: "β1選択的遮断薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "enp",
    generic: "エナラプリル",
    brand: "レニベース",
    category: "ACE阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "sotal",
    generic: "ソタロール",
    brand: "ソタコール",
    category: "クラスIII抗不整脈薬・β遮断薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "dabi",
    generic: "ダビガトラン",
    brand: "プラザキサ",
    category: "直接トロンビン阻害薬（DOAC）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "riva",
    generic: "リバーロキサバン",
    brand: "イグザレルト",
    category: "直接Xa因子阻害薬（DOAC）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "apix",
    generic: "アピキサバン",
    brand: "エリキュース",
    category: "直接Xa因子阻害薬（DOAC）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "edox",
    generic: "エドキサバン",
    brand: "リクシアナ",
    category: "直接Xa因子阻害薬（DOAC）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "metf",
    generic: "メトホルミン",
    brand: "メトグルコ / グリコラン",
    category: "ビグアナイド系経口血糖降下薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "sita",
    generic: "シタグリプチン",
    brand: "グラクティブ / ジャヌビア",
    category: "DPP-4阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "alog",
    generic: "アログリプチン",
    brand: "ネシーナ",
    category: "DPP-4阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "lina",
    generic: "リナグリプチン",
    brand: "トラゼンタ",
    category: "DPP-4阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "empa",
    generic: "エンパグリフロジン",
    brand: "ジャディアンス",
    category: "SGLT2阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "dapa",
    generic: "ダパグリフロジン",
    brand: "フォシーガ",
    category: "SGLT2阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "pregab",
    generic: "プレガバリン",
    brand: "リリカ",
    category: "Ca2+チャネルα2δサブユニット阻害薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "gabap",
    generic: "ガバペンチン",
    brand: "ガバペン",
    category: "抗てんかん薬・神経障害性疼痛治療薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "leve",
    generic: "レベチラセタム",
    brand: "イーケプラ",
    category: "抗てんかん薬",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "morph",
    generic: "モルヒネ",
    brand: "モルヒネ塩酸塩 / MSコンチン / カディアン",
    category: "オピオイド（μ受容体作動薬）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "tram",
    generic: "トラマドール",
    brand: "トラマール / ワントラム",
    category: "オピオイド（弱オピオイド・SNRI様作用）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "allop",
    generic: "アロプリノール",
    brand: "ザイロリック / アロシトール",
    category: "キサンチンオキシダーゼ阻害薬（尿酸生成抑制）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "febux",
    generic: "フェブキソスタット",
    brand: "フェブリク",
    category: "キサンチンオキシダーゼ阻害薬（非プリン型）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "colch",
    generic: "コルヒチン",
    brand: "",
    category: "抗痛風薬（チュービリン重合阻害）",
    form: "注射",
    features: ["renal"],
  },
  {
    id: "famo",
    generic: "ファモチジン",
    brand: "ガスター",
    category: "H2受容体拮抗薬",
    form: "注射",
    features: ["renal"],
  },
];

if (typeof module !== 'undefined') module.exports = { DRUG_MASTER };